import fs                                    from 'fs'
import matter                                from 'gray-matter'
import dynamic                               from 'next/dynamic'
import path                                  from 'path'
import React                                 from 'react'
import { Container, Divider, Heading, Text } from 'theme-ui'

import Link                          from '@components/Link'
import Layout                        from '@layouts/BaseLayout'
import { postFilePaths, POSTS_PATH } from '@utils/mdxUtils'

const Globe = dynamic(() => import('@components/Globe/Globe'))

const Index = ({ posts }) => {
  return (
    <Container>

      <Heading>Handling</Heading>

      <Divider />

      <Text variant='styles.h2'>
        Click the link below to navigate to a page generated by{' '}
        <code>next-mdx-remote</code>.
      </Text>

      <Globe />

      <ul>
        {posts.map((post) => (
          <li key={post.filePath}>
            <Link href={`/content/${post.filePath.replace(/\.mdx?$/, '')}`}>
              {post.data.title}
            </Link>
          </li>
        ))}
      </ul>
    </Container>
  )
}

export function getStaticProps() {
  const posts = postFilePaths.map((filePath) => {
    const source = fs.readFileSync(path.join(POSTS_PATH, filePath))
    const { content, data } = matter(source)

    return {
      content,
      data,
      filePath
    }
  })

  return { props: { posts } }
}

Index.Layout = Layout

export default Index
